### PR TITLE
[AD-324] Ensure literal types are formatted correctly

### LINKED ISSUE #202: [BUG] Time literals are not formatted correctly
## Environment
- DocumentDB JDBC driver version: v1.0.0
- DocumentDB server version: 3.6, 4.0
- OS: Any
- BI Tool or client name: Any
- BI Tool or client version: Any
- Java version (if known):  Java 8

---

## Problem Description
1. Steps to reproduce:   

- Connect to any database either using a Java application or BI tool. 
- Execute a query containing a time literal such as  `SELECT TIME '20:17:40' FROM collection` 
- Error occurs when retrieving result set. 

2. Expected behaviour:  Time value can be retrieved and displayed.
3. Actual behaviour: Query fails with error message - `Conversion between the source type (Integer) and the target type (Date) is not supported.`
4. Error message/stack trace:  
```
Conversion between the source type (Integer) and the target type (Date) is not supported.
java.sql.SQLException: Conversion between the source type (Integer) and the target type (Date) is not supported.
	at software.amazon.documentdb.jdbc.common.utilities.SqlError.createSQLException(SqlError.java:191)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getValue(DocumentDbAbstractResultSet.java:173)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getDate(DocumentDbAbstractResultSet.java:317)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getTime(DocumentDbAbstractResultSet.java:335)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getTime(DocumentDbAbstractResultSet.java:249)
Caused by: org.apache.commons.beanutils.ConversionException: Default conversion to java.sql.Date failed.
	at org.apache.commons.beanutils.converters.AbstractConverter.handleMissing(AbstractConverter.java:314)
	at org.apache.commons.beanutils.converters.AbstractConverter.handleError(AbstractConverter.java:269)
	at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:177)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getValue(DocumentDbAbstractResultSet.java:171
```
---

## Screenshots
- NA

---

## JDBC log
```
Created projection stages of pipeline.
Pipeline stages added: {$project: {'EXPR$0': {"$literal": 73060000}, _id: 0}}
Query 1926e6b5-33f4-4e5a-84a3-a2cfdcfaedc6: Took 2057 ms to translate query.
Sending command '{"aggregate": "collection", "pipeline": [{"$project": {"EXPR$0": {"$literal": 73060000}, "_id": 0}}], "cursor": {"batchSize": 2000}, "$db": "resultDatabase", "lsid": {"id": {"$binary": {"base64": "qpsgQdszQWOv3kr6DfGdVQ==", "subType": "04"}}}}' with request id 46 to database resultDatabase on connection [connectionId{localValue:9, serverValue:10}] to server localhost:55921
Execution of command with request id 46 completed successfully in 13.97 ms on connection [connectionId{localValue:9, serverValue:10}] to server localhost:55921
Query 1926e6b5-33f4-4e5a-84a3-a2cfdcfaedc6: Took 36 ms to execute query and retrieve first batch of results.
Query 1926e6b5-33f4-4e5a-84a3-a2cfdcfaedc6: Executed on collection collection with following pipeline operations: [{"$project": {"EXPR$0": {"$literal": 73060000}, "_id": 0}}]
Converting 'Integer' value '73060000' to type 'java.sql.Date'
    IntegerConverter cannot handle conversion to 'java.sql.Date'
    Conversion threw ConversionException: IntegerConverter cannot handle conversion to 'java.sql.Date'
    IntegerConverter cannot handle conversion to 'java.sql.Date'
Conversion between the source type (Integer) and the target type (Date) is not supported.
```

### PR DESCRIPTION
**Pull request by andiemontoyeah**
### Summary
- Ensure  literal types BOOLEAN, TINYINT, SMALLINT, INT, BIGINT, DECIMAL, NUMERIC, FLOAT, REAL, DOUBLE, CHAR, VARCHAR, BINARY, VARBINARY, TIME, DATE, TIMESTAMP , YEAR TO MONTH INTERVAL types and DAY TO SECOND INTERVAL type are formatted correctly and can be retrieved in ResultSet.

### Description
- Add unit tests for literal types BOOLEAN, TINYINT, SMALLINT, INT, BIGINT, DECIMAL, NUMERIC, FLOAT, REAL, DOUBLE, CHAR, VARCHAR, BINARY, VARBINARY, TIME, DATE, TIMESTAMP , YEAR TO MONTH INTERVAL types and DAY TO SECOND INTERVAL types.
- Add handling in visitLiteral() in DocumentDbRules for any missed types.

### Related Issue
https://bitquill.atlassian.net/browse/AD-324

### Additional Reviewers
@affonsoBQ
@andiem-bq
@alexey-temnikov
@birschick-bq

### CODE REVIEW

File: calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java [hunk 1]
```diff
@@ -577,24 +599,12 @@ private static Operand getMongoAggregateForOperator(
...
             final List<Operand> strings,
             final String stdOperator) {
-        verifySupportedType(call);
         if (hasObjectIdAndLiteral(call, strings)) {
             return new Operand(getObjectIdAggregateForOperator(call, strings, stdOperator));
         }
         return new Operand("{" + maybeQuote(stdOperator) + ": [" + Util.commaList(strings) + "]}");
     }
 
-    private static void verifySupportedType(final RexCall call)
```
Comment (andiemontoyeah) [inline calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java:587]: moved this check to be under trandlateDateAdd specifically since we do support simple interval + interval addition for months and years.

**Review by affonsov — APPROVED** [review]
LGTM

**Review by affonsov — APPROVED** [review]

File: calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java [hunk 2]
```diff
@@ -382,22 +383,43 @@ protected RexToMongoTranslator(final JavaTypeFactory typeFactory,
             }
 
             switch (literal.getType().getSqlTypeName()) {
-                case DOUBLE:
                 case DECIMAL:
```
Comment (birschick-bq) [inline calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java:387]: DECIMAL should be its own case [mapped](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#mongodb-bsontype-Decimal128) to `$numberDecimal` instead of `$numberDouble`. Is there a separate case for NUMERIC? Or is that just DECIMAL?

File: calcite-adapter/src/test/java/software/amazon/documentdb/jdbc/query/DocumentDbQueryMappingServiceLiteralTest.java [hunk 3]
```diff
@@ -285,4 +285,174 @@ void testSelectQueryForObjectId() throws SQLException {
...
+                                + "\"literalUnknown\": null, \"_id\": 0}}"),
+                result1.getAggregateOperations().get(0));
+
+        // Numeric literals
+        final String query2 = String.format(
+                "SELECT CAST(-128 AS TINYINT) AS \"literalTinyInt\", "
+                        + "CAST(-32768 AS SMALLINT) AS \"literalSmallInt\", "
+                        + "CAST(-2147483648 AS INT) AS \"literalInt\", "
+                        + "CAST(-9223372036854775808 AS BIGINT) AS \"literalBigInt\", "
+                        + "CAST(123.45 AS DECIMAL(5, 2)) AS \"literalDecimal\", "
```
Comment (birschick-bq) [inline calcite-adapter/src/test/java/software/amazon/documentdb/jdbc/query/DocumentDbQueryMappingServiceLiteralTest.java:319]: See comment about DECIMAL to `$numberDecimal`. You'll want to test with a number that will exceed the 64-bit Double range.

File: calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java (hunk 1 above)
Comment (birschick-bq) [reply calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java:587]: All good.

File: calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java (hunk 2 above)
Comment (andiemontoyeah) [reply calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java:387]: DocumentDB doesn't support the 128 bit decimal type 
And yup! Numeric = Decimal.

Comment (andiemontoyeah) [reply calcite-adapter/src/main/java/software/amazon/documentdb/jdbc/calcite/adapter/DocumentDbRules.java:387]: Added TODO

**Review by birschick-bq — APPROVED** [review]
